export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const USER_SERVICE = Symbol('USER_SERVICE');
export const TOKEN_PROVIDER = Symbol('TOKEN_PROVIDER');
export const GOOGLE_STRATEGY_PROVIDER = Symbol('GOOGLE_STRATEGY_PROVIDER');
