/** @type {import('prettier').Config & import('prettier-plugin-tailwindcss').PluginOptions} */
const config = {
  endOfLine: "lf",
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "all",
  bracketSpacing: true,
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "<BUILTIN_MODULES>",
    "^lucide-react$",
    "^@leww/(.*)$",
    "",
    "^types$",
    "^~/types$",
    "^~/config/(.*)$",
    "^~/components/shared/(.*)$",
    "^~/components/(.*)$",
    "^~/hooks$",
    "^~/lib$",
    "^~/utils$",
    "^~/constants$",
    "^~/styles/(.*)$",
    "^~/features/(.*)$",
    "^~/app/(.*)$",
    "",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  tailwindAttributes: ["tw"],
  tailwindFunctions: ["cva"],
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
};

export default config;
